ECC-1539
hmrc/eori-common-component-registration-frontend pull request #202
Opened 2023-02-07 11:31 UTC by dinamit1984

2023-02-07 14:04 UTC, RobertLaverick requested changes

2023-02-07 14:04 UTC, RobertLaverick commented on app/uk/gov/hmrc/eoricommoncomponent/frontend/views/how_can_we_identify_you_utr.scala.html
> +    if(orgType.etmpOrgTypeCode == "0003") messages("subscription-journey.how-confirm-identity.utr.hint")
Right, this magic strings - without hunting it down it's hard to know what on earth a 0003 means. Lets have a quick catchup

2023-02-08 11:40 UTC, RobertLaverick approved these changes

2023-02-08 16:24 UTC, vasanthavijaya approved these changes

2023-02-08 16:27 UTC, merged