ECC-1701 - Cache not cleared when user selecting OrgType
hmrc/eori-common-component-registration-frontend pull request #280
Opened 2023-04-20 12:36 UTC by JakeGoodwin

2023-04-20 12:59 UTC, dinamit1984 submitted a review, later dismissed

2023-04-20 14:31 UTC, RobertLaverick requested changes

2023-04-20 14:31 UTC, RobertLaverick commented on app/uk/gov/hmrc/eoricommoncomponent/frontend/services/RegistrationDetailsService.scala
> +    ).flatMap(_ => saveRegistrationDetails(organisationType))
Considering the ticket, lets have tests to prove that the cache is in fact cleared.

2023-04-24 13:47 UTC, RobertLaverick approved these changes

2023-04-24 14:28 UTC, merged