ECC-1825 work in progress
hmrc/eori-common-component-registration-frontend pull request #313
Opened 2023-06-14 13:34 UTC by dinamit1984

2023-06-21 12:01 UTC, RobertLaverick requested changes

2023-06-21 14:07 UTC, dinamit1984 commented on app/uk/gov/hmrc/eoricommoncomponent/frontend/viewModels/CheckYourDetailsRegisterViewModel.scala
> +    ) || cdsOrgType.contains(CdsOrganisationType.ThirdCountryIndividual)
As Rob suggested  Will raise a spike to investigate how we use our CDS org types

2023-06-21 14:08 UTC, dinamit1984 commented on test/unit/viewModels/CheckYourDetailsRegisterViewModelSpec.scala
> +    Seq(Some(CdsOrganisationType.SoleTrader), Some(CdsOrganisationType.ThirdCountrySoleTrader))
As Rob suggested  Will raise a spike to investigate how we use our CDS org types

2023-06-29 09:58 UTC, burns238 approved these changes

2023-07-03 13:59 UTC, burns238 requested changes

2023-07-03 13:59 UTC, burns238 commented on app/uk/gov/hmrc/eoricommoncomponent/frontend/viewModels/CheckYourDetailsRegisterViewModel.scala
> +        )
Something like this @dinamit1984 :

```    
    val (registeredAddress, addressCall) = (isUserIdentifiedByRegService, subscription.addressDetails) match {
      case (false, Some(address)) => 
        (addressViewModelHtml(address), ConfirmContactDetailsController.form(service, isInReviewMode = true))
      case _ => 
        (addressHtml(registration.address), SixLineAddressController.showForm(isInReviewMode = true, organisationType = orgType, service))
    }

    val registeredAddressRow = Seq(
      summaryListRow(
        key = businessDetailsLabel(isPartnership, cdsOrgType),
        value = Some(registeredAddress),
        call = Some(addressCall)
      )
    )```

2023-07-03 13:59 UTC, burns238 commented on app/uk/gov/hmrc/eoricommoncomponent/frontend/viewModels/CheckYourDetailsRegisterViewModel.scala
> +      )
This as well ^

2023-07-03 15:08 UTC, burns238 approved these changes

2023-07-04 09:43 UTC, merged