ECC-1752 removing hint text for NINO
hmrc/eori-common-component-registration-frontend pull request #329
Opened 2023-06-27 07:17 UTC by dinamit1984

2023-06-27 12:55 UTC, RobertLaverick submitted a review, later dismissed

2023-06-28 08:27 UTC, JakeGoodwin requested changes

2023-06-28 08:27 UTC, JakeGoodwin commented on app/uk/gov/hmrc/eoricommoncomponent/frontend/views/match_nino_row_individual.scala.html
> +    <p class="govuk-body">@messages("cds.matching.nino.row.description")</p>
Since we're changing this anyway, could we improve it using the paragraph helper, it'll look cleaner

2023-06-28 08:27 UTC, JakeGoodwin commented on app/uk/gov/hmrc/eoricommoncomponent/frontend/views/match_nino_row_individual.scala.html
> +@(matchNinoIdForm: Form[NinoMatchModel]  ,service: Service)(implicit request: Request[_], messages: Messages)
Very minor but may as well mention it since the other change is going to be made. Can the comma be moved back - just looks a bit odd

2023-06-28 09:54 UTC, JakeGoodwin approved these changes
We could swap around `id: Option[String] = None, text: String = "", html: Option[Html] = None` to be ` text: String = "", id: Option[String] = None, html: Option[Html] = None` so we don't need to include an Id but it's not a problem to have it included. approved

2023-06-30 07:20 UTC, JakeGoodwin approved these changes

2023-06-30 07:26 UTC, merged