ECC-2013: VatCustomerInformation API calls added
hmrc/eori-common-component-registration-frontend pull request #404
Opened 2023-09-07 10:38 UTC by JakeGoodwin

2023-09-08 13:33 UTC, burns238 requested changes

2023-09-08 13:33 UTC, burns238 commented on app/uk/gov/hmrc/eoricommoncomponent/frontend/services/GetVatCustomerInformationService.scala
> +    } yield getVatCustomerInformationConnector.getVatCustomerInformation(vrn.getOrElse(""))
We shouldn't call this where we don't have a vrn - it needs to sit within a map

2023-09-08 13:33 UTC, burns238 commented on app/uk/gov/hmrc/eoricommoncomponent/frontend/services/GetVatCustomerInformationService.scala
> +      format.parse(oldResponse.dateOfReg.getOrElse("")) == newResponse.effectiveRegistrationDate.getOrElse(new Date())
```
    val postCodeMatches: Option[Boolean] = (for {
     oldPostcode <- oldResponse.postcode
     newPostcode <- newResponse.postCode
    } yield oldPostcode == newPostcode).getOrElse(false)

    val dateMatches = (for {
      oldDateString <- oldResponse.dateOfReg
      oldDate = format.parse(oldDateString)
      newDate <- newResponse.effectiveRegistrationDate
    } yield oldDate == newDate).getOrElse(false)
```

2023-09-13 11:56 UTC, burns238 submitted a review, later dismissed

2023-09-15 08:52 UTC, dinamit1984 approved these changes

2023-09-15 10:34 UTC, merged