ECC-1118| migration to hmrc-mongo, updating dependencies WIP
hmrc/eori-common-component-registration-frontend pull request #73
Opened 2022-09-05 10:15 UTC by oliwiaKot

2022-09-07 10:57 UTC, darbyo requested changes

2022-09-07 11:20 UTC, oliwiaKot commented on app/uk/gov/hmrc/eoricommoncomponent/frontend/services/cache/sessionCache.scala
> +  val regDetailsKey                    = "regDetails"     //
typo, removed now

2022-09-07 11:20 UTC, oliwiaKot commented on app/uk/gov/hmrc/eoricommoncomponent/frontend/services/cache/sessionCache.scala
> +  val groupEnrolmentKey                = "groupEnrolment" //
removed

2022-09-07 11:32 UTC, oliwiaKot commented on app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/GYEHowCanWeIdentifyYouNinoController.scala
> +  // TODO Get rid of `.get`. Now if there is no information Exception will be thrown, understand what must happen if this is not provided
ticket created https://jira.tools.tax.service.gov.uk/browse/ECC-1283

2022-09-07 11:51 UTC, beckfordp commented
Once we made the decision to replace the SessionCache with on that extends SessionCacheRepository from hmrc-mongo then the interface to the cache changes and this change becomes huge. I questioned the value of doing so at the time when we did it in subscription... but its done now, and at least our session caches are now consistent with each other and the rest of hmrc :)

- checked that the hmrc-mongo SessionCache was being used

2022-09-07 12:00 UTC, beckfordp commented
Once we made the decision to change the interface to the SessionCache by extending SessionCacheRepository from hmrc-mongo, this refactor became huge :) I questioned the value at the time when we did so in subscription... but its done now, and both our session caches are now consistent with each other and other projects that use hmrc-mongo.

- Checked that the SessionCache now extends SessionCacheRepository from hmrc-mongo
- Reviewed the ripple effect the change in the SessionCache interface has caused (implicit request params etc).
- All compiles, and the tests are all passing locally.

LGTM 👍

2022-09-07 13:04 UTC, poscala commented on app/uk/gov/hmrc/eoricommoncomponent/frontend/services/cache/sessionCache.scala
> +      case _ => Future.successful(None)
I would recommend changing this to filter out fatal JVM exceptions as we shouldn't catch those, e.g. we need to let the app crash `OutOfMemmoryError`.

Can be achieved using `case NonFatal(e) => ...`

More info: https://stackoverflow.com/a/66118268, https://stackoverflow.com/questions/29744462/the-difference-between-nonfatal-and-exception-in-scala

2022-09-07 13:06 UTC, poscala commented on app/uk/gov/hmrc/eoricommoncomponent/frontend/services/cache/sessionCache.scala
> +        case _ => Future.successful(false)
Same as in my other comment about handling Non Fatal JVM exceptions

2022-09-07 16:14 UTC, poscala approved these changes

2022-09-07 19:29 UTC, beckfordp approved these changes

2022-09-12 10:32 UTC, darbyo approved these changes

2022-09-12 10:43 UTC, merged